import { defineConfig } from 'oxfmt';

export default defineConfig({
  allowComments: true,
  allowTrailingCommas: true,
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  experimentalSortImports: {
    groups: [
      ['builtin'],
      ['external'],
      ['internal'],
      ['parent', 'sibling', 'index'],
      ['style'],
    ],
    ignoreCase: true,
    internalPattern: ['@/**'],
    newlinesBetween: true,
    order: 'asc',
    partitionByComment: false,
    partitionByNewline: false,
    sortSideEffects: true,
  },
  experimentalSortPackageJson: true,
  ignorePatterns: [
    'src/components/ui/*',
    '_dev/**/*',
    '_devlogs/**/*',
    '.next/**/*',
    '.kilo/**/*',
    '.vscode/**/*',
    'node_modules/**/*',
    '.env*',
    '*.md',
    'AGENT.md',
    'CLAUDE.md',
    'components.json',
    'FUNDING.md',
    'LICENSE',
    'next-env.d.ts',
    'next.config.ts',
    'pnpm-lock.yaml',
    'postcss.config.mjs',
    'tsconfig.json',
    'tsconfig.tsbuildinfo',
    'public/**/*',
    'tools/**/*',
    'build/**/*',
    'dist/**/*',
    '.opencode/**/*',
    '.storybook/**/*',
    'e2e/**/*',
    'playwright-report/**/*',
    'test-results/**/*',
    'supabase/**/*',
    'src/lib/supabase/**/*',
    'src/lib/__tests__',
  ],
  insertFinalNewline: true,
  jsxSingleQuote: true,
  objectWrap: 'preserve',
  printWidth: 88,
  quoteProps: 'as-needed',
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
});
